### ISSUE TITLE
Python file "panicked"; index out of bounds

### ISSUE THREAD

**Issue by tasmussen15** [sergeant-savage/vexdoc#11]
Set up config file for Python, properly annotated one function, including title, summary, and `# ENDVEXDOC`. Upon running `vexdoc generate`, documentation fails:
![image](https://github.com/user-attachments/assets/fb0235f1-840d-44f8-a820-3310c63cca6d)

**Comment by tasmussen15** [comment]
Code screenshots in case of user error:
![image](https://github.com/user-attachments/assets/1d95a360-cf5f-42da-9d25-a48aae71ba48)
![image](https://github.com/user-attachments/assets/d8d6f8b6-f794-4736-83fc-6aaf32ad938d)

**Comment by mariano-f-r** [comment]
Right, we've encountered this before, it's  because I sent you a bugged build. I'll send you another build in a bit.

**Comment by tasmussen15** [comment]
Fixed build works, no issue.
