### ISSUE TITLE
vexdoc not generating documentation

### ISSUE THREAD

**Issue by HyruleCoCo** [sergeant-savage/vexdoc#14]
When i tried to run vexdoc on my code earlier today it wouldnt properly generate the code giving the error "failed to write documentation for insert file name here due to incorrect annotations caused by: section titles must be followed by a summary” i included images of my code to help discern the issue- hopefully it is user error but who knows
![image](https://github.com/user-attachments/assets/5d3c83b3-281d-4124-8b44-b7209fcea9c6)
![image](https://github.com/user-attachments/assets/8f9b62bb-7e4b-4510-8407-771d78ac06a6)

**Comment by mariano-f-r** [comment]
Hi, you spelled summary as "summery".
