### ISSUE TITLE
VexDoc documents directories that are marked to ignore if they have a space in them

### ISSUE THREAD

**Issue by mariano-f-r** [sergeant-savage/vexdoc#3]
Using the config in #1 and the code from [this repo](https://github.com/Darksabre1500/SpinUp499M), running the binary causes vexcode to ignore the directive to ignore.

**Comment by SilverScan** [comment]
Can confirm on windows

**Comment by mariano-f-r** [comment]
Turns out this issue is caused by failing to respect capitalization for ignored directories. Clarified in  #8
